# Generated by Django 3.0.6 on 2020-05-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("product_url", models.URLField(unique=True)),
                ("fabelio_product_id", models.IntegerField(null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
            options={"db_table": "products",},
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("unit_price", models.IntegerField(default=0)),
                ("unit_sale_price", models.IntegerField(default=0)),
            ],
            options={"db_table": "product_prices",},
        ),
    ]
